name: base
channels:
- conda-forge
dependencies:
- cudatoolkit=11.6.0
- numpy=1.22.4
- pillow=9.1.1
- pip=22.1.2
- python=3.9.13
- pytorch::pytorch=1.12.1=py3.9_cuda11.6_cudnn8.3.2_0
- pytorch::torchvision=0.13.1=py39_cu115
- scipy=1.8.1
- ffmpeg=5.0.1
- tqdm=4.64.0
- mlflow=1.28.0
- dvc=2.26.2